### ISSUE TITLE
Allow input card name in string instead of numerical value for card argument in configuration file

### ISSUE THREAD

**Issue by doumdi** [introlab/odas#1]
Instead of writing :
`
    # Input with raw signal from microphones
    interface: {
        type = "soundcard";
        card = 3;
        device = 0;
    }
`

Would be great to be able to write :

`
    # Input with raw signal from microphones
    interface: {
        type = "soundcard";
        card = "8SoundsUSB";
        device = 0;
    }
`
So we can avoid card number mistakes when opening the interface.

**Comment by FrancoisGrondin** [comment]
This is now possible thanks to @Slothologist which added this feature here: #24
