### ISSUE TITLE
Matrix creator project

### ISSUE THREAD

**Issue by magic-dave** [introlab/odas#107]
Good afternoon,

The matrix creator demo works exactly as required, but I am trying to extract the raw angle prediction. I cannot seem to find where you are providing or calculating the direction of approach data.

Any advice you have on how I can get this data would be greatly appreciated.

Thank you,
Dave

**Comment by jake266637** [comment]
Did you end up finding a solution?

**Comment by magic-dave** [comment]
Good morning,


Yes, this ticket can be closed. I had forgotten about this.


Thank you,

Dave

________________________________

**Comment by jake266637** [comment]
What was the solution?

**Comment by magic-dave** [comment]
The angle is determined in increase_pots() using the X and Y coordinates of the sound source. It is in a variable called angle_xy - you can assign the value to a variable that is accessible anywhere. I had a variable called holder that was used to carry the angle data from the increase_pots() function elsewhere using ROS.

**Comment by jake266637** [comment]
Oh great thanks
