### ISSUE TITLE
odas with respeaker 6-mic array

### ISSUE THREAD

**Issue by goldenqwerty** [introlab/odas#113]
tried using the respeaker 6mic array with the following [config file](https://github.com/xiongyihui/odas/blob/master/config/odaslive/respeaker_6_mic_array.cfg)

similar to issue #39 , 
there is an error:
Source hops: Cannot set sample format: Invalid argument.

tried changing the nBits to 16,24,32 but all did not work.
Is there anything wrong with the config settings?

**Comment by taospartan** [comment]
What does  arecord -l  say?

**Comment by goldenqwerty** [comment]
card 1: seeed8micvoicec [seeed-8mic-voicecard], device 0: bcm2835-i2s-ac10x-codec0 ac10x-codec0-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by goldenqwerty** [comment]
i guess its seeed8micvoice as i have added the:

# Seeed Voicecard
ATTR{id}=="seeed8micvoicec",ATTR{number}=="1",ENV{PULSE_PROFILE_SET}="seeed-voicecard.conf"

in 

/lib/udev/rules.d/90-pulseaudio.rules

as suggested [here](http://wiki.seeedstudio.com/ReSpeaker_6-Mic_Circular_Array_kit_for_Raspberry_Pi/)

**Comment by taospartan** [comment]
Have you tried recording audio with arecord?

**Comment by goldenqwerty** [comment]
Yeah arecord works. Audacity too

**Comment by goldenqwerty** [comment]
arecord -Dac108 -f S32_LE -r 16000 -c 8 a.wav

**Comment by taospartan** [comment]
Change this

potential: { format = "json"; interface: { type = "socket"; ip = "127.0.0.1"; port = 9001; };
To this

potential: { format = "undefined"; interface: {             type = "blackhole"; };

And

tracked: { format = "json"; interface: { type = "socket"; ip = "127.0.0.1"; port = 9000; }; };

To

tracked: { format = "undefined"; interface: { type = "blackhole";  }; };

Then let me know

**Comment by goldenqwerty** [comment]
it's the same issue:
+--------------------------------------------+
|    ODAS (Open embeddeD Audition System)    |
+--------------------------------------------+
| Author:  Francois Grondin                  |
| Email:   francois.grondin2@usherbrooke.ca  |
| Website: introlab.3it.usherbrooke.ca       |
| Version: 1.0                               |
+--------------------------------------------+
| + Initializing configurations...... [Done] |
| + Initializing objects............. [Done] |
| + Launch threads................... [Done] |
| + Threads running.................. Source hops: Cannot set sample format: Invalid argument

**Comment by goldenqwerty** [comment]
not sure if i'm doing the right thing:
before i run this 
(pi@raspberrypi:~/odas $ ./bin/odaslive -c ./config/respeaker_6_mic_array.cfg -v),

 i also do this  pi@raspberrypi:~/Download/odas_web-0.2-alpha $ npm start

**Comment by goldenqwerty** [comment]
arecord -L gives the following (is it normal that the default is through Pulseaudio sound server?):

null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
ac108
dmixer
ac101
sysdefault:CARD=seeed8micvoicec
    seeed-8mic-voicecard, 
    Default Audio Device
dmix:CARD=seeed8micvoicec,DEV=0
    seeed-8mic-voicecard, 
    Direct sample mixing device
dsnoop:CARD=seeed8micvoicec,DEV=0
    seeed-8mic-voicecard, 
    Direct sample snooping device
hw:CARD=seeed8micvoicec,DEV=0
    seeed-8mic-voicecard, 
    Direct hardware device without any conversions
plughw:CARD=seeed8micvoicec,DEV=0
    seeed-8mic-voicecard, 
   Hardware device with all software conversions

**Comment by goldenqwerty** [comment]
@xiongyihui please give some advice on this issue where odas is giving " Source hops: Cannot set sample format: Invalid argument" using the respeaker 6 mic array

**Comment by xiongyihui** [comment]
Sorry, I made a mistake, the sample bits must be 32, then it should work. I just tested it. 

A modified version which outputs message to terminal instead of socket is:
[respeaker_6_mic_array.cfg](https://github.com/introlab/odas/files/2336124/respeaker_6_mic_array.txt)

Do you use pulseaudio?

**Comment by goldenqwerty** [comment]
@xiongyihui 
yea I used 32bit but mine wasnt working; 
yea the pulse audio was installed for the snowboy doa function (under step 2 of play with snowboy as suggested in this [link](http://wiki.seeedstudio.com/ReSpeaker_6-Mic_Circular_Array_kit_for_Raspberry_Pi/)
is the pulseaudio messing with the config?

**Comment by xiongyihui** [comment]
Maybe uninstall pulseaudio and just read audio from alsa.

**Comment by goldenqwerty** [comment]
working now, i was pointing to a wrong config file hahaha

**Comment by deeprobo-dev** [comment]
sudo aplay -l run this in terminal to know what is your card no and put it in odas.cfg file
