### ISSUE TITLE
Correlating the audio files to the DOA information

### ISSUE THREAD

**Issue by jake266637** [introlab/odas#134]
I am currently trying to correlate the 4 different sound recordings in postfiltered audio file to the 4 most significant events. So that i can associate the recording streams with a direction of arrival. I altered the "potential:' section in matrix_creator.cfg so that the output was in json format but fed  into a raw file i can open. I also altered the postfiltered and separated files so that a raw file was created.

Also not sure what the difference between postfiltered and separated is, i am opening both with 16-bit encoding, 4 channels, little-endian and 16000Hz but they both appear quite similar.

**Comment by yihanhu97** [comment]
Hi were you able to figure out the difference between postfiltered and separated? Thank you
