### ISSUE TITLE
Post-filtering "ss" method

### ISSUE THREAD

**Issue by bentarnold** [introlab/odas#144]
I couldn't find any of your publications that discuss the "ss" post-filtering method used in ODAS. There was plenty of material discussing the "ms" post-filtering method. Could you point me to where I might find a theoretical description of the "ss" method found in the `mod_sss_process_sspf` function?

**Comment by FrancoisGrondin** [comment]
Hi Ben,

This hasn't been published yet. Please feel free to ask your questions here and I'll answer them in this thread.

**Comment by bentarnold** [comment]
Did you base this method off of a previously developed method? Is there a plan to publish it at some point? I read through the code and pulled out the corresponding mathematics. I have a couple of questions about getting some intuition behind what the method does. But I think I'll go through it in more detail first so I can ask you more intelligent questions. Great project by the way. It's been enjoyable looking through it and figuring out how it's organized.

**Comment by balkce** [comment]
I'm definitely listening to this thread.
