### ISSUE TITLE
Processing audio in ODAS

### ISSUE THREAD

**Issue by Mopele** [introlab/odas#170]
Hey, 
I would like to kind of use ODAS to get the DOA for a wav file in an iterval of 0.5sec. Would that be possible with ODAS. Or is there a way to save the data from the graphs to use them later on in, for example a machine learning project? 
Kindly, 
Moritz Pfennig. 
PS: I am really a noob...

**Comment by bartengine27** [comment]
yes, you can, check the config of the SSS and record sections on https://github.com/introlab/odas_web

**Comment by Mopele** [comment]
> yes, you can, check the config of the SSS and record sections on https://github.com/introlab/odas_web

Ok, but I am not familiar with js so is there maybe a way to implement it into python? If not, is there a more in depth wiki of the odas project, because as i see it there is ne real explanation of how to accualy save some data from the analytics right?

Btw thanks for the fast response @bartengine27
