### ISSUE TITLE
starting odas Error Sink pots

### ISSUE THREAD

**Issue by Mopele** [introlab/odas#171]
Hey, I try to run ODAS like this: .`/odaslive -c ../config/odaslive/respeaker_4_mic_array.cfg`.
My error looks like this: `+--------------------------------------------+
|    ODAS (Open embeddeD Audition System)    |
+--------------------------------------------+
| Author:  Francois Grondin                  |
| Email:   francois.grondin2@usherbrooke.ca  |
| Website: introlab.3it.usherbrooke.ca       |
| Version: 1.0                               |
+--------------------------------------------+
| + Initializing configurations...... [Done] |
| + Initializing objects............. [Done] |
| + Launch threads................... Sink pots: Cannot connect to server
`
If I look at the config everything looks like it should. Is there a way to make it work?

**Comment by ajaygunalan** [comment]
Hey,

I'm also having the same issue. How did you solve it?

**Comment by Mopele** [comment]
> 
> 
> Hey,
> 
> I'm also having the same issue. How did you solve it?

You have to start the odas live first. So you open the odas GUI interface and then start the odas client. The explanation is, that you have to have the odas server running to connet to it via the sockets of the odaslive command. If you dont want to use a odas server then have a look in te odasconfig for the respeaker. If you have any more questions just ask ;-)

**Comment by jiguansghen** [comment]
?

**Comment by guelermus** [comment]
Hi,

I saw an interface called Terminal. 
Would it be possible to use it with odaslive without a need for odasserver?

Best,
