### ISSUE TITLE
Spatial Filter configuration 

### ISSUE THREAD

**Issue by taospartan** [introlab/odas#19]
Could you give some guidance on how to correctly use the spatial filter to block false detections?

Many thanks

Tao

**Comment by FrancoisGrondin** [comment]
Do you know where the false detections come from? Reflections from walls or the floor?

**Comment by taospartan** [comment]
It appears to be the floor

Many thanks

**Comment by FrancoisGrondin** [comment]
Ok, then what you should do is aim the vector at the ceiling, and choose the angles to infer a gain of zero in the direction of the floor. Suppose the z-axis points to the ceiling:

```
    spatialfilter: {

        direction = ( +0.000, +0.000, +1.000 );
        angle = (80.0, 90.0);

};    
```
This configuration means that you allow a gain of 1 between angle 0 and 80, then there is a smooth transition in the gain from 1 to 0 and the angle range from 80 to 90, and finally the gain is 0 between 90 and 180 degrees. In other words, the system does not listen to what comes from the floor. Here's a drawing to illustrate what this parameter does:

![spatialdirection](https://user-images.githubusercontent.com/4040041/37793252-78f38c2e-2de4-11e8-85ac-b556169e8bd6.png)

**Comment by taospartan** [comment]
That’s brilliant thank you very much, this is such a great piece of software!!

**Comment by alexengbloom** [comment]
Cool. Hello, @FrancoisGrondin . Does this also apply when using the matrix voice (microphones on the same plane) ?

link to matrix voice: https://www.matrix.one/products/voice
