### ISSUE TITLE
Any difference between odas and manyears? 

### ISSUE THREAD

**Issue by zhaoforever** [introlab/odas#2]
Hi  Francois,
      I have used the manyears project and it works well, and the papers you provided helps a lot. As for the odas project, is there any difference between the odas and manyears? If so, would provide some papers for reference? Thanks.

**Comment by FrancoisGrondin** [comment]
Yes many differences. ODAS is meant to be faster, more robust to various microphone array shapes, and in some cases improve sound source separation. Papers are on the way, and documentation is currently being written in the wiki. A demo video will be released soon. Stay tuned!

**Comment by zhaoforever** [comment]
@FrancoisGrondin Thanks for the demo video. The noise cancellation and sound source separation results seem great! Looking forward to the wiki.
