### ISSUE TITLE
Installation instructions omit a cd command

### ISSUE THREAD

**Issue by scotthasse** [introlab/odas#20]
The installation instructions at:

git clone https://github.com/introlab/odas.git --branch=dev

omit a `cd odas` command which should be run before making and changing to the build directory.

Also, if you want to have an (effectively) empty build directory already in the repository, you can add the directory to git with a .gitignore like the following:

```
# Ignore everything in this directory
*
# Except this file
!.gitignore
```
to avoid putting built files under revision control.

**Comment by doumdi** [comment]
Thanks! I have made the change to the documentation. Also, I changed the default branch to master. I want to avoid empty directories in the git repository.
