### ISSUE TITLE
Listening to the mic audio via soundcard 

### ISSUE THREAD

**Issue by Eric-cyber-1024** [introlab/odas#204]
Is it possible for the odaslive to run the SST on the terminal and also output an audio signal via the soundcard ?  In my project, I am trying to gather the DOA of the sound source but also with the audible signal for voice recognition. Is anyone here could guide me to the right direction in generating this signal ? 

Huge Thanks 
Eric

**Comment by henrik-the** [comment]
Did you solve this issue? If yes, how did you do it?
