### ISSUE TITLE
Printing the live "tracks.txt" results

### ISSUE THREAD

**Issue by keenanfitzharris** [introlab/odas#216]
Hello! Thank you for the incredible library of software. I have recently been trying to use ODAS for a project - which currently utilizes the Azure Kinect DK microphone array. So far, odaslive is working well for me. In addition to saving the results in the "tracks.txt" format, is it possible to print the live data results into a UI? 

I would just need the XYZ coordinates of the possible source and angle of arrival. I would like to show the results of odaslive to my colleagues in real time rather than saving them into a file. 

Thanks!

**Comment by hltkts123** [comment]
Have you solved this problem yet?
