### ISSUE TITLE
Connection from ::ffff:192.168.0.30 closed

### ISSUE THREAD

**Issue by TheCyberDesk** [introlab/odas#217]
Hello,

I'm running into an issue which is driving me crazy here. I've followed the steps to get ODAS Web set up on my RPi 4.

I am running Node version 10.21.0.

I've set up the respeaker_4_mic_array config file to be using the correct card and device index. I've also tried it with 127.0.0.1 and the ip of 192.168.0.30

Each time I try pressing the green launch button on odas studio, the connections open and then immediately close. 

Please can I have some help with this?

Cheers,

**Comment by VioletIsSoCute** [comment]
May I asked how you solved the issue?
