### ISSUE TITLE
Socket error: "Sink pots: Cannot connect to server"

### ISSUE THREAD

**Issue by LudovicDeMatteis** [introlab/odas#226]
Hello,
I've been working with odas_ros and the 16SoundsUSB card. It is plugged in my computer and I ran the odas ros package.

The part of the configuration that is most interesting for this issue is:

potential: {

        format = "json";

        interface: {
            type = "socket";
            ip = "127.0.0.1";
            port = 9001;
        };

        #format = "undefined";

        #interface: {
        #   type = "blackhole";
        #};

    };
    
When running the node that launches Odas I get the following error: Sink pots: Cannot connect to server
That certainly means that the card cannot acces the socket at IP 127.0.0.1:9001. I'm not experienced with networks so I don't know how to fix this issue. Any help would be welcome.

Many thanks

Ludovic

**EDIT:**
I also have a doubt on this part of the configuration file:
`raw: 
{

    fS = 16000;
    hopSize = 512;
    nBits = 32;
    nChannels = 16; 

    # Input with raw signal from microphones
    interface: {
        type = "soundcard";
        card = 1;
        device = 0;
    }

}`

I found the card and device number with `arecord -l`

**Comment by doumdi** [comment]
@LudovicDeMatteis, Can you try to use the latest (just released last week) odas_ros code here: https://github.com/introlab/odas_ros ? Use the sample configuration in here to start : https://github.com/introlab/odas_ros/blob/main/config/configuration.cfg

**Comment by doumdi** [comment]
@LudovicDeMatteis, could you describe in details what you are trying to achieve? Basically, the odas_core_node needs to connect to a python node and you seem to have a configuration mismatch  (wrong port?). We simplified the setup in the new version parsing directly only one configuration file avoiding this problem.

**Comment by LudovicDeMatteis** [comment]
@doumdi I used the latest version of odas_ros and the configuration file you suggested. I seems to have gotten past the socket error. I now encounter a python error:
`OdasServerNode instance has no attribute '_sst_frame_id'
OdasServerNode instance has no attribute '_ssl_frame_id'
`
It most likely happens in the odas_server_node.py file in "send_sst" line 188:
`odas_sst_array_stamped_msg.header.frame_id = self._sst_frame_id` where sst_frame_id may not have been initialized.

To describe further what I want to achieve: I have a 16SoundUSB card connected to my computer and I'd like to get the informations about the sources positions in ROS. So I would use oda_ros to publish in topics that I can read from in other nodes.

**Comment by LudovicDeMatteis** [comment]
I defined a frame_id that suits my aplication and I past the error. I now got a new one concerning pcl2.
`[ERROR] [1617719530.472705]: bad callback: <bound method OdasVisualizationNode._ssl_cb of <__main__.OdasVisualizationNode instance at 0x7f04ed2e0500>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ludovic/gitLab/speech_dialogue_new/src/odas_ros/scripts/odas_visualization_node.py", line 82, in _ssl_cb
    pcl = pcl2.create_cloud(header,fields,cloud_points)
NameError: global name 'pcl2' is not defined
`

**Comment by doumdi** [comment]
@LudovicDeMatteis You need to put the odas_ros package in the src directory of the catkin workspace and do a "catkin_make" to generate the adequate ROS messages. Then, you should launch (with roslaunch) your project by creating a launch file similar to this one : https://github.com/introlab/odas_ros/blob/main/launch/odas.launch.

**Comment by oliroy92** [comment]
Hi @LudovicDeMatteis, 

I just pushed a new version of odas_ros with modifications to fix these errors. Can you try again after having pulled?

Thanks!

**Comment by doumdi** [comment]
@LudovicDeMatteis Please tell us if you are successful with the patch. Thanks!

**Comment by LudovicDeMatteis** [comment]
@doumdi @oliroy92  Everything is working fine now. I can read the topics and visualize on rviz which is exactly what I wanted. Thanks a lot for your help. Have a nice day

**Comment by LudovicDeMatteis** [comment]
Hi, I'm reopening this issue because I facing new problems. 

To summarize, I got a Ubuntu 18.04 computer with a 16SoundUSB card plugged in (USB). Using the given config file I can run odas_ros and get published topics. However, looking at the topic `odas/sst/sources` I do not get any sources detected. 

I tried to set the soundcard as the acquisition device in Audacity to verify that it gets something and sound is indeed detected.

Problems may come from the configuration file. I ran `arecord -l` to verify that the card number is correct and I got the following output:
```
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC255 Analog [ALC255 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC255 Alt Analog [ALC255 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: D20 [16SoundsUSB Audio 2.0], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```
Hence the configuration file interface being: 
```
raw: 
{
    fS = 16000;
    hopSize = 512;
    nBits = 32;
    nChannels = 16; 
    # Input with raw signal from microphones
    interface: {    #"arecord -l" OR "aplay --list-devices" to see the devices
        type = "soundcard_name";
        devicename = "hw:CARD=1,DEV=0";
    }
}
```

I don't know what else to test or check. 

Thanks,
Ludovic

**Comment by oliroy92** [comment]
Hi @LudovicDeMatteis,

Normally, with the latest release of odas_ros, the topic for the sound source tracking (sst) should be published on the topic `/odas/sst`. If you are able to launch odas_ros and it doesn't crash, it should mean that your sound card is recognized. When you do launch odas_ros with `roslaunch`, you should be able to set the `rviz` parameter to true to see the published sst in Rviz. You can also specify a configuration file path if you want to. 

``` 
roslaunch odas_ros odas.launch rviz:=true configuration_path:=~/catkin_ws/path_to_config_file/.../configuration.cfg
```

If you execute this, you should be able to see the published topic for the sound source tracking and sound source localization (if enabled in configuration file) visually:

![image](https://user-images.githubusercontent.com/43940456/114401931-5b483280-9b71-11eb-984f-72d556b74de6.png)

If you can't see anything, it may be because of a incorrect configuration file. Your sound card configuration looks to be correct, so it could be the socket configuration.

Can you try this and see if data appears on rviz? If you have a doubt about your configuration file, you can use the one that is on the repository, it should work (only change your sound card number and device number like you did).

Olivier

**Comment by LudovicDeMatteis** [comment]
Hi @oliroy92 

I ran the command to run rviz with odas.launch and I indeed get points from the ssl topic. However there is no arrow showing up even when there is a sound source. When the sound source gets louder the number of points reduces so I assume the card is indeed getting some sound and there is less potential sources when the main source is clearer.

 In the terminal I get some messages: `Extra data: line 8 column 1 - line 15 column 1 (char 168 - 336)`
 
![image](https://user-images.githubusercontent.com/58736393/114417644-ada54580-9ba9-11eb-9616-2bfa0b6c3b62.png)

This may be related to the fact that Sound Source Tracking is not giving results. 

Note that I changed the configuration file to have the correct positions and orientations on my 8 microphones and that I only map microphones 1 to 8:

> mapping:
{
    map: (1, 2, 3, 4, 5, 6, 7, 8);
}


Thanks,
Ludovic

**Comment by LudovicDeMatteis** [comment]
The dots of the ssl point cloud are mostly red to yellow in the direction of the source unlike in your picture where they are mostly green. There may be a problem of intensity?

The topic `/odas/sst` is published but the "sources" field is empty :
![image](https://user-images.githubusercontent.com/58736393/114524090-d3c7f580-9c3c-11eb-99ad-ea6eaf35e291.png)

Here is a picture of the microphone array configuration. Unfortunately I don't have a CAD file available. The microphone numbers on the pictures are not corresponding to how they really are plugged in the card but I double-checked the microphones positions (the mu) and their directions in the config file to verify that it is correct (with microphone i being plugged at port i on the card).

Attached is the config file I used.

[configuration.zip](https://github.com/introlab/odas/files/6302465/configuration.zip)

**Comment by doumdi** [comment]
@LudovicDeMatteis, can you try increasing the gains on each microphone (there is a blue multi-turn potentiometer for that)? To help, I use Audacity to make sure I turn in the right direction to increment the gain & amplitude while making an acquisition. Please try the maximum gain for the 8 microphones you use. You should hear a "click" from the potentiometer when you reach the end of the range.

**Comment by oliroy92** [comment]
@LudovicDeMatteis,

In addition to what @doumdi said, here are a couple more things to look at:

> Here is a picture of the microphone array configuration. 

Could you make sure to include that picture in your comment?

From your configuration file, it looks like the microphone configuration is a semi-circle with microphones of alternating heights. Is that correct? Also, you seem to have configured your file with 16 microphones but have only 8 mapped. Is there a reason why you would not use all 16? And if there is only 8 microphones on your array, maybe you could remove microphones 9 to 16 from your configuration file.

If I'm not mistaken, there seems to be an error for the direction of Microphone #5 in your configuration file. 
![image](https://user-images.githubusercontent.com/43940456/114626900-5a52f600-9c82-11eb-8954-5ed0e4ab3d73.png)
The direction should be set to `direction = ( 0.9238795325, 0.3826834324, 0 );`

Olivier

**Comment by LudovicDeMatteis** [comment]
@doumdi @oliroy92 the microphone gains are already set to the maximum.

> Could you make sure to include that picture in your comment?

Sorry, I didn't see that the picture was not attached. Here it is now: 
![IMG_20210413_093416_resized_20210413_093520292](https://user-images.githubusercontent.com/58736393/114728348-ed4d6800-9d36-11eb-966b-f19831cc771a.jpg)

Indeed it is a semi circle with microphones of alternating heights. I had a couple mistakes in my configuration file that I fixed now. 
We use only 8 microphone because of constraints on the robot it will be implemented on. The laboratory will certainly use a 8SoundsUSB instead of the 16SoundsUSB in the future.

Thus only 8 microphones are mapped. When I try to remove microphones 10 to 16 from the configuration file it seems to work better (points are plotted with better intensity in the points cloud) but I cannot remove microphone 9 from the configuration file otherwise it raises the error `Sink tracks: Cannot connect to server` and `Sink hops: Cannot connect to server`. These errors disappear as soon as I add a 9th microphone to the configuration file. This seems to happen even if I map microphones 1-7 instead of 1-8. 

When I remove microphones from the config file I also got more often the message I mentioned previously: 

> In the terminal I get some messages: `Extra data: line 8 column 1 - line 15 column 1 (char 168 - 336)`

However, the red arrow is now appearing and following the source. The problem was certainly a intensity problem that have been solved by removing some microphones from the configuration file.

**Comment by LudovicDeMatteis** [comment]
@doumdi @oliroy92 Hi, I got one more question. Is odas_ros capable of separating two sources and gives both their positions? I suppose that the SSL topic can be used to get the most probable positions of two (or more) source but will the SSS et SST topics give distinct positions and audio?
Thanks,
Ludovic

**Comment by doumdi** [comment]
@LudovicDeMatteis , yes ODAS can track and separate up to 4 sources.

**Comment by mamadouDembele** [comment]
Hi I am currently working with the respeaker 4 mic array voice interface. I'm trying to find the location of the sound source thanks to the odas_ros packages. After compiling this package, when I run the launch, I first get this error '' Sink tracks: Cannot connect to server''
![Screenshot from 2021-04-29 11-01-13](https://user-images.githubusercontent.com/57793779/116527716-4a225400-a8db-11eb-9fa3-90f5b0dc15d3.png)

I said to myself as I had not launched odas studio, the error is surely due to that. So I first launched odas studio (npm start) then the launch file (roslaunch odas_ros odas.launch) I get a new error "error: [Errno 98] Address already in use".
![Screenshot from 2021-04-29 11-02-24](https://user-images.githubusercontent.com/57793779/116527838-64f4c880-a8db-11eb-88b2-a49d322192fa.png)

Could someone help me
