### ISSUE TITLE
Cannot find the bin folder in the code. Where do I find it?

### ISSUE THREAD

**Issue by jenniferyennam** [introlab/odas#259]
The binary(bin) folder is much needed during the installation of the ODAS Studio. As it is needed too during the implementation in the ODAS. Where do I find and install the bin folder for smooth installation and implementation in ODAS Studio.

**Comment by philippewarren** [comment]
The `bin` folder should be back, although it is now in your CMAKE_BINARY_DIR and won't appear amidst your sources
