### ISSUE TITLE
Granular processing

### ISSUE THREAD

**Issue by GodCed** [introlab/odas#34]
Only process modules where a sink is specified.

**Comment by FrancoisGrondin** [comment]
Currently being done on branch "granular". The valve/avalve objects are ready, I now need to incorporate them in the pipeline. Will keep you updated when this is ready.

**Comment by FrancoisGrondin** [comment]
This is now implemented in the branch [granular](https://github.com/introlab/odas/tree/granular). ODAS no longer processes computations for modules which content is not fed in a sink.
