### ISSUE TITLE
Respeaker V.1

### ISSUE THREAD

**Issue by satell** [introlab/odas#41]
I have respeaker 7 mics array version one 
https://www.seeedstudio.com/ReSpeaker-Mic-Array-Far-field-w%2F-7-PDM-Microphones-p-2719.html

is it compatible with odas ? if yes can you please let me know what is recommended content of configuration file for it ?

**Comment by xiongyihui** [comment]
@satell You need change to the raw audio firmware of the mic array. If you have not done it, go to https://github.com/respeaker/mic_array_dfu to download the firmware and the DFU tool.

**Comment by FrancoisGrondin** [comment]
I'll close this issue for now. Feel free to reopen if you have other questions.
