### ISSUE TITLE
what is meaning of sst activity?

### ISSUE THREAD

**Issue by xfqjklw** [introlab/odas#50]
Hey,the sst module print the below info:
    "timeStamp": 1062,
    "src": [
        { "id": 1, "tag": "dynamic", "x": -0.925, "y": -0.117, "z": 0.361, "activity": 1.000 },
        { "id": 7, "tag": "dynamic", "x": 0.710, "y": -0.192, "z": 0.677, "activity": 0.000 },
        { "id": 0, "tag": "", "x": 0.000, "y": 0.000, "z": 0.000, "activity": 0.000 },
        { "id": 0, "tag": "", "x": 0.000, "y": 0.000, "z": 0.000, "activity": 0.000 }
    ]
}
what is meaning of activity?
Thank you very much.

**Comment by FrancoisGrondin** [comment]
Hi,

It tells you if the tracked source is currently active or not for the given frame. In other words, when you speak you have silence periods, but the system keeps tracking you if these are short. Silence will result in a value close to 0, and activity in a value close to 1.

Cheers!
