### ISSUE TITLE
Is there any paper or document about the algorithm theory in odas?

### ISSUE THREAD

**Issue by xfqjklw** [introlab/odas#51]
I like the odas very much,I want to know more about odas.
Is there any paper or document about the algorithm theory in odas?
Thank you very much.

**Comment by FrancoisGrondin** [comment]
Hi!
I'm currently writing a paper, which should be available soon on Arxiv. Stay tuned!

**Comment by xfqjklw** [comment]
Oh,Wonderful.
If you publish the paper,Please inform us.
Thank you.
