### ISSUE TITLE
Beam shape

### ISSUE THREAD

**Issue by taospartan** [introlab/odas#60]
Is it possible to change the properties of the pattern or shape of the ‘beam’ when using static targets?

Many thanks

**Comment by taospartan** [comment]
Also is the Beamforming additive or differential?

Cheers :)

**Comment by FrancoisGrondin** [comment]
Hey there!

For now only delay and sum beamforming or GSS is performed. Will consider this as a future feature to implement!

**Comment by taospartan** [comment]
Excellent:), so I’m assuming the pattern can’t be changed?

**Comment by FrancoisGrondin** [comment]
As for now, no :'(
