### ISSUE TITLE
normalised Vectors

### ISSUE THREAD

**Issue by taospartan** [introlab/odas#64]
In the SST are the vectors meant to add up to 1 exactly or is it rounded ?

{ "id": 2, "tag": "dynamic", "x": 0.417, "y": 0.047, "z": 0.908, "activity": 0.973 }

cheers:)

**Comment by FrancoisGrondin** [comment]
You should get the following:

x^2 + y^2 + z^2  = 1.0

And activity should lie between 0 and 1

Cheers!
