### ISSUE TITLE
How does plotting work?

### ISSUE THREAD

**Issue by alexengbloom** [introlab/odas#67]
I am modifying mod_ssl_process in mod_ssl.c. Even after I comment out the code that handles ssl calculation, I see a lot of points being plotted on the ODAS WEB as shown in the images below. The values seem to be randomly generated as the plotted values change whenever I restart odascore; it does not change after boot. 

Could you explain why this is happening so that I can understand the issue? 

<img width="1201" alt="screen shot 2018-05-30 at 17 41 23" src="https://user-images.githubusercontent.com/39780526/40749579-8106f6ec-6432-11e8-8c2b-25d3c8d95dff.png">
<img width="1189" alt="screen shot 2018-05-30 at 17 43 32" src="https://user-images.githubusercontent.com/39780526/40749581-812fc220-6432-11e8-84ce-7362b6ad0eee.png">
<img width="1199" alt="screen shot 2018-05-30 at 17 44 07" src="https://user-images.githubusercontent.com/39780526/40749582-8143a1be-6432-11e8-8468-85bbcfc6698b.png">
<img width="1196" alt="screen shot 2018-05-30 at 17 44 51" src="https://user-images.githubusercontent.com/39780526/40749583-8155c678-6432-11e8-972d-0a99f97c0042.png">

**Comment by FrancoisGrondin** [comment]
It seams that as you are commenting the SSL processing, the system does not compute any beamforming energy on the sphere. It then tries to find the maximum values on non-initialized arrays, which can lead to this random result.

**Comment by luc2yj** [comment]
Thank you. I have fixed the problem!

**Comment by alexengbloom** [comment]
The problem can be fixed by commenting out `obj->nPots = 0;` from function `pots_zero(pots_obj * obj)`.
