### ISSUE TITLE
Some question about mode of sss.

### ISSUE THREAD

**Issue by huotuichang1** [introlab/odas#70]
Excuse me,
I see there is mvdr in the sss_mode but there is not any code.why?Is it not effective?

**Comment by FrancoisGrondin** [comment]
It is not implemented yet. MVDR uses a lot of computing resources, and was not real time on a raspberry pi. Is this something you'd need?

**Comment by huotuichang1** [comment]
you are great~thank you~

**Comment by taospartan** [comment]
What does MVDR stand for?

**Comment by FrancoisGrondin** [comment]
A MVDR is good to eliminate "equally" all sounds coming from other directions than the desired one. From my limited experience with MVDR, here are the two drawbacks I observed:

1) When you have strong reflections generated by the desired source, these are considered as undesirable interference, and the MVDR tries to attenuate frequency bands that shouldn't be attenuated as they contain the target signal information. 
2) You need to compute and invert the correlation matrix at each frequency band, which requires significant computing resources
