### ISSUE TITLE
a small sugesstion.

### ISSUE THREAD

**Issue by huotuichang1** [introlab/odas#71]
In the matrix.c,the function matrix_det,
    float matrix_det(const matrix_obj * obj) {

        float a00, a01, a02, a10, a11, a12, a20, a21, a22;
        float det;

        det = 0.0f;

        if ((obj->nRows == 3) && (obj->nCols == 3)) {

            a00 = obj->array[0*obj->nRows+0];
            a01 = obj->array[0*obj->nRows+1];
            a10 = obj->array[1*obj->nRows+0];
            a11 = obj->array[1*obj->nRows+1];

            det = a00*a11 - a01*a10;

        }
        //printf("det1 %f\n",det);

        if ((obj->nRows == 3) && (obj->nCols == 3)) {

            a00 = obj->array[0*obj->nRows+0];
            a01 = obj->array[0*obj->nRows+1];
            a02 = obj->array[0*obj->nRows+2];
            a10 = obj->array[1*obj->nRows+0];
            a11 = obj->array[1*obj->nRows+1];
            a12 = obj->array[1*obj->nRows+2];
            a20 = obj->array[2*obj->nRows+0];
            a21 = obj->array[2*obj->nRows+1];
            a22 = obj->array[2*obj->nRows+2];

            det = a00*a11*a22 - a00*a12*a21 - a01*a10*a22 + a01*a12*a20 + a02*a10*a21 - a02*a11*a20;        

        }
        //printf("det2 %f\n",det);
        return det;
in the first "if",maybe it should be if ((obj->nRows == 2) && (obj->nCols == 2)) .

**Comment by FrancoisGrondin** [comment]
Good point! I sometimes get distracted when I code for too long :) Will fix that, thanks!
