### ISSUE TITLE
Uma-16 minidsp

### ISSUE THREAD

**Issue by taospartan** [introlab/odas#84]
François , have you had a play with the 16 mic array from minidsp yet? 

Cheers Tao

**Comment by FrancoisGrondin** [comment]
Minidsp sent me one, but I need to play with it didn't had time yet! Any issues on your side?

**Comment by taospartan** [comment]
Not yet, I’m just playing around with targeted beam-forming, seeing how well odas can separate sound sources within 30 degrees of each other with the array in a vertical orientation.

Without odas I’ve recorded 32bit samples at 96khz  of bird song and it’s remarkable!!
