### ISSUE TITLE
Connection closed after running odas

### ISSUE THREAD

**Issue by zengjiutian** [introlab/odas#91]
Description:
odas_web started by "npm start" in laptop and odas started by "./odaslive -c matrix_voice.cfg" on pi, i can see the new client connection in terminal of laptop. But soon later the connection closed. When i use "./odaslive -c matrix_voice.cfg -v" , the same problem shows. 
Could you please help me solve this problem ?
Thanks !
<img width="335" alt="1" src="https://user-images.githubusercontent.com/10195620/42730698-a1b3e610-882d-11e8-865f-cf44be3d0deb.png">
<img width="371" alt="2" src="https://user-images.githubusercontent.com/10195620/42730700-a77115dc-882d-11e8-97ed-ef2407f67cb5.png">

￼

**Comment by albertmend** [comment]
Did you find the problem?

**Comment by solodezaldivar** [comment]
Would be interested in a solution if anyone found one!

**Comment by skainen** [comment]
Still no solution?
