### ISSUE TITLE
How can I get the direction of a plane (not hemisphere).

### ISSUE THREAD

**Issue by alexengbloom** [introlab/odas#92]
How can I get the direction of a plane (not hemisphere). In otherwords, just 360 degrees in ODAS WEB.
I found that simply setting the z value to 0.0 in ssl does not work. Is there a quick way to do this?

**Comment by FrancoisGrondin** [comment]
Yep, I suggest you set z to 0.0, and then renormalize the x-y values to a norm of 1. For now there is no other way... good to know this is a feature that might be interesting for some user.

**Comment by alexengbloom** [comment]
Thanks!
