### ISSUE TITLE
General instructions to read direction and angle

### ISSUE THREAD

**Issue by pkalebu** [introlab/odas#99]
I'm unsure how to get started with the library. I have it installed as per the wiki, but don't know how to read out the localization data without using the visualization tool. I am using a ReSpeaker USB 4-mic array. Does anyone know how I can go about reading out the raw localization values?

**Comment by FrancoisGrondin** [comment]
You can print the potential/tracked sources in the terminal, is that what you are looking for?

**Comment by FrancoisGrondin** [comment]
You can change the config file like this:

```
    # Output to export tracked sources
    tracked: {

        format = "json";

        interface: {
            type = "terminal";
        };
    };
```

**Comment by pkalebu** [comment]
Awesome, thanks!
